const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={top:'Community banner',arrests:'Daily Arrests',footer:'Bottom banner'};let csrf='',configured=true,data={ads:[],inquiries:[]};
const setupToken=new URLSearchParams(location.hash.slice(1)).get('setup')||'';if(location.hash)history.replaceState(null,'',location.pathname);
function message(text,error=false){$('message').hidden=!text;$('message').textContent=text;$('message').classList.toggle('error',error);}
async function api(action,body){const options={cache:'no-store',credentials:'same-origin'};if(body!==undefined){options.method='POST';options.headers={'X-CSRF-Token':csrf};if(body instanceof FormData)options.body=body;else{options.headers['Content-Type']='application/json';options.body=JSON.stringify(body);}}const response=await fetch('ads-api.php?action='+action,options);const result=await response.json();if(!response.ok)throw new Error(result.error||'Request failed');if(result.csrf)csrf=result.csrf;return result;}
async function init(){try{const s=await api('session');configured=s.configured;$('auth').hidden=s.signedIn;$('dashboard').hidden=!s.signedIn;$('logout').hidden=!s.signedIn;if(s.signedIn)await refresh();else if(!configured){$('authTitle').textContent='Set up your admin account';$('authNote').textContent=setupToken?'Choose a username and a password of at least 14 characters. This setup link works only once.':'Open the private setup link provided to the site owner.';$('authForm').hidden=!setupToken;$('authSubmit').textContent='Create admin account';$('authForm').elements.password.minLength=14;$('authForm').elements.password.autocomplete='new-password';}}catch(e){message(e.message,true);}}
async function refresh(){data=await api('dashboard');const active=data.ads.filter(a=>a.status==='active');$('activeCount').textContent=active.length;$('leadCount').textContent=data.inquiries.filter(i=>i.status==='new').length;$('rateTotal').textContent=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(active.reduce((n,a)=>n+Number(a.monthly_rate)/100,0));for(const k of Object.keys(labels))$('slotsForm').elements[k].checked=data.slots[k];$('adList').innerHTML=data.ads.length?data.ads.map(a=>`<article class="row"><div><strong>${esc(a.business)}</strong> <span class="badge">${esc(a.status)}</span><p>${esc(a.headline)}</p><p class="muted">${labels[a.slot]} · ${esc(a.area)} · $${(a.monthly_rate/100).toFixed(2)}/month<br>${esc(a.start_date||'Any start date')} → ${esc(a.end_date||'No end date')}</p></div><div class="actions"><button data-edit="${a.id}">Edit</button><button data-toggle="${a.id}">${a.status==='active'?'Pause':'Activate'}</button></div></article>`).join(''):'<p>No ads yet. Create an ad when a sponsor is ready.</p>';$('inquiryList').innerHTML=data.inquiries.length?data.inquiries.map(i=>`<article class="row"><div><strong>${esc(i.business)}</strong><p>${esc(i.name)} · ${esc(i.email)}${i.phone?' · '+esc(i.phone):''}</p><p>${esc(i.message)}</p><p class="muted">${esc(labels[i.slot]||'Placement undecided')} · ${esc(new Date(i.created_at).toLocaleString())}</p></div><label>Status<select data-inquiry="${i.id}">${['new','contacted','closed'].map(s=>`<option ${s===i.status?'selected':''}>${s}</option>`).join('')}</select></label></article>`).join(''):'<p>No advertising inquiries yet.</p>';}
$('authForm').onsubmit=async ev=>{ev.preventDefault();$('authSubmit').disabled=true;try{await api(configured?'login':'setup',{...Object.fromEntries(new FormData(ev.target)),token:setupToken});message('');await init();}catch(e){message(e.message,true);}finally{$('authSubmit').disabled=false;}};
$('logout').onclick=async()=>{try{await api('logout',{});location.reload();}catch(e){message(e.message,true);}};
function imagePreview(){const name=$('adForm').elements.image.value;$('imageInfo').innerHTML=name?`<img src="ads-image.php?file=${encodeURIComponent(name)}" alt="Ad image preview">`:'';}
function edit(a){const f=$('adForm');f.reset();for(const k of ['id','business','category','headline','body','phone','email','image','slot','area','status','start_date','end_date','monthly_rate','notes'])if(f.elements[k])f.elements[k].value=a?.[k]??({id:0,category:'Attorney',slot:'top',area:'all',status:'draft',monthly_rate:0}[k]??'');f.elements.monthly_rate.value=(a?.monthly_rate||0)/100;$('editorTitle').textContent=a?'Edit ad':'Create an ad';$('editorMessage').textContent='';imagePreview();$('editor').showModal();}
$('newAd').onclick=()=>edit();$('closeEditor').onclick=()=>$('editor').close();$('removeImage').onclick=()=>{$('adForm').elements.image.value='';$('imageFile').value='';imagePreview();};
$('adList').onclick=async ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.edit)edit(data.ads.find(a=>a.id===Number(b.dataset.edit)));if(b.dataset.toggle){b.disabled=true;try{const a=data.ads.find(a=>a.id===Number(b.dataset.toggle));await api('status',{id:a.id,status:a.status==='active'?'paused':'active'});await refresh();}catch(e){message(e.message,true);b.disabled=false;}}};
$('adForm').onsubmit=async ev=>{ev.preventDefault();$('saveAd').disabled=true;try{const file=$('imageFile').files[0];if(file){if(file.size>4000000)throw new Error('Choose an image under 4 MB.');const upload=new FormData();upload.append('image',file);const r=await api('upload',upload);ev.target.elements.image.value=r.image;$('imageFile').value='';imagePreview();}await api('save',Object.fromEntries(new FormData(ev.target)));$('editor').close();await refresh();message('Ad saved.');}catch(e){$('editorMessage').textContent=e.message;}finally{$('saveAd').disabled=false;}};
$('slotsForm').onsubmit=async ev=>{ev.preventDefault();try{await api('slots',Object.fromEntries(Object.keys(labels).map(k=>[k,ev.target.elements[k].checked])));message('Placements saved.');await refresh();}catch(e){message(e.message,true);}};
$('inquiryList').onchange=async ev=>{if(!ev.target.dataset.inquiry)return;try{await api('inquiry-status',{id:Number(ev.target.dataset.inquiry),status:ev.target.value});await refresh();message('Inquiry updated.');}catch(e){message(e.message,true);}};
$('passwordForm').onsubmit=async ev=>{ev.preventDefault();try{await api('password',Object.fromEntries(new FormData(ev.target)));ev.target.reset();message('Password updated.');}catch(e){message(e.message,true);}};
init();
