<?php
header('Cache-Control: no-store');
header('X-Frame-Options: DENY');
header('Referrer-Policy: no-referrer');
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Admin · Local CrimeWatch</title><link rel="stylesheet" href="admin.css?v=2"><script type="module" src="admin.js?v=2"></script><script type="module" src="analytics-admin.js?v=1"></script><script type="module" src="push-admin.js?v=1"></script></head>
<body><header><a href="./">◎ CrimeWatch <small>LOCAL ADMIN</small></a><button id="logout" hidden>Sign out</button></header><main>
<div id="message" role="status" hidden></div>
<section id="auth" class="panel narrow" hidden><p class="eyebrow">OWNER ACCESS</p><h1 id="authTitle">Sign in</h1><p id="authNote">Manage advertising and business inquiries.</p><form id="authForm"><label>Username<input name="username" autocomplete="username" maxlength="80" required></label><label>Password<input name="password" type="password" autocomplete="current-password" maxlength="200" required></label><button class="primary" id="authSubmit">Sign in</button></form></section>
<section id="dashboard" hidden><div class="heading"><div><p class="eyebrow">YOUR ADVERTISING DESK</p><h1>Local reach. Local business.</h1><p>Manage sponsors, placements, and advertising inquiries.</p></div><button id="newAd" class="primary">+ Create an ad</button></div>
<div class="stats"><div><strong id="activeCount">0</strong><span>Active ads</span></div><div><strong id="leadCount">0</strong><span>New inquiries</span></div><div><strong id="rateTotal">$0</strong><span>Active monthly rates · not payments</span></div></div>
<section class="panel"><div class="heading"><div><p class="eyebrow">PRIVATE · OWNER ONLY</p><h2>Audience &amp; ad performance</h2></div><label>Reporting period<select id="analyticsDays"><option value="7">Last 7 days</option><option value="30" selected>Last 30 days</option><option value="90">Last 90 days</option></select></label></div><p id="analyticsNote" role="status">Loading audience measurements…</p><div id="audienceStats" class="stats audience-stats"></div><div class="actions"><button id="refreshAnalytics">Refresh analytics</button><a id="salesReport" href="sales-report.php?days=30">View private sales report</a><a id="audienceCsv" href="analytics-api.php?action=export&amp;days=30">Download aggregate CSV</a></div><p class="muted">Only signed-in admins can view analytics or export reports. Saved reports contain aggregate numbers, without reader contact details. You choose whom to share them with.</p><details><summary>How these numbers are measured</summary><p>Counts start when this feature went live. Daily visitors are approximate, based on a daily-changing identifier; do not add daily counts and call them monthly unique people. Ad views require 50% visibility for one second. Profile opens are on-site clicks, not calls or sales. Counts are deduplicated per page visit, community and placement. Opt-outs, blockers and bots affect totals. Signed-in owner traffic is excluded. Only verified emails count as registered readers.</p></details><h3>Daily traffic</h3><div id="trafficTable" class="table-wrap"></div><h3>Paid ad performance</h3><div id="adPerformance" class="table-wrap"></div><h3>Community readership</h3><p id="communityStats"></p></section>
<section class="panel"><h2>Reader accounts · private</h2><p>Contact details are available only to you here and are never included in sales reports. Pending email verification is not counted as a registered reader.</p><div id="readerList" class="table-wrap"></div><div class="actions"><button id="readerPrev">← Previous</button><span id="readerPage"></span><button id="readerNext">Next →</button></div></section>
<section class="panel"><h2>Ad placements</h2><p>Enabled spaces show an “Advertise here” message when there is no matching sponsor. Ads stay on this website.</p><form id="slotsForm" class="placements"><label><input type="checkbox" name="top"> Community banner</label><label><input type="checkbox" name="arrests"> Daily Arrests</label><label><input type="checkbox" name="footer"> Bottom banner</label><button>Save placements</button></form></section>
<section class="panel"><h2>Your ads</h2><p>Dates use Central Time. Multiple eligible ads share a placement, selected on each page visit.</p><div id="adList"></div></section>
<section class="panel"><h2>Advertising inquiries</h2><p>Website inquiries are saved here. Contact email: info@crimewatch.live. Email messages are managed separately in your mailbox.</p><div id="inquiryList"></div></section>
<section class="panel"><h2>App notifications</h2><p>Send an announcement to verified readers who opted in on their iPhones. Creating a draft does not send it.</p><p id="pushStatus" role="status"></p><form id="pushForm"><div class="fields"><label>Title<input name="title" maxlength="80" required></label><label>Audience<select name="area"><option value="all">All opted-in readers</option><option value="polk">Polk County</option><option value="shsu">Huntsville — SHSU</option><option value="houston">Houston</option><option value="shsu-conroe">Conroe — SHSU</option><option value="shsu-woodlands">The Woodlands — SHSU</option><option value="sfa">Nacogdoches — SFA</option><option value="forney">Forney</option><option value="nolan">Nolan County</option><option value="kaufman">Kaufman County</option></select></label><label class="wide">Message<textarea name="body" maxlength="240" required></textarea></label></div><button>Preview notification</button></form><div id="pushReview" hidden><p id="pushPreview"></p><form id="pushSend"><label>Type SEND to queue this message<input name="confirm" pattern="SEND" required autocomplete="off"></label><button>Send reviewed notification</button></form></div><h3>Notification history</h3><div id="pushHistory"></div></section><details class="panel"><summary>Account security</summary><form id="passwordForm" class="narrow"><label>Current password<input type="password" name="current" autocomplete="current-password" required></label><label>New password · at least 14 characters<input type="password" name="password" autocomplete="new-password" minlength="14" maxlength="200" required></label><button>Update password</button></form></details>
</section></main>
<dialog id="editor"><div class="heading"><h2 id="editorTitle">Create an ad</h2><button id="closeEditor" aria-label="Close editor">×</button></div><form id="adForm"><input type="hidden" name="id" value="0"><input type="hidden" name="image"><div class="fields">
<label>Business name<input name="business" maxlength="100" required></label><label>Business type<select name="category"><option>Attorney</option><option>Bail bonds</option><option>Local business</option></select></label>
<label class="wide">Headline<input name="headline" maxlength="100" required></label><label class="wide">Business profile<textarea name="body" rows="4" maxlength="1600" required></textarea></label>
<label>Phone<input name="phone" type="tel" maxlength="40"></label><label>Email<input name="email" type="email" maxlength="160"></label>
<label>Placement<select name="slot"><option value="top">Community banner</option><option value="arrests">Daily Arrests</option><option value="footer">Bottom banner</option></select></label>
<label>Community<select name="area"><option value="all">All communities</option><option value="polk">Polk County</option><option value="shsu">Huntsville — SHSU</option><option value="houston">Houston</option><option value="shsu-conroe">Conroe — SHSU</option><option value="shsu-woodlands">The Woodlands — SHSU</option><option value="sfa">Nacogdoches — SFA</option><option value="forney">Forney</option><option value="nolan">Nolan County</option><option value="kaufman">Kaufman County</option></select></label>
<label>Status<select name="status"><option value="draft">Draft</option><option value="active">Active</option><option value="paused">Paused</option></select></label><label>Monthly rate ($) · internal record<input name="monthly_rate" type="number" min="0" max="100000" step="0.01" value="0"></label>
<label>Start date · optional<input name="start_date" type="date"></label><label>End date · optional<input name="end_date" type="date"></label>
<label class="wide">Ad image · JPG, PNG, WebP under 4 MB<input id="imageFile" type="file" accept="image/jpeg,image/png,image/webp"></label><div class="wide" id="imageInfo"></div><button id="removeImage" type="button">Remove image</button>
<label class="wide">Private notes<textarea name="notes" maxlength="2000" rows="2"></textarea></label></div><p id="editorMessage" role="status"></p><button class="primary" id="saveAd">Save ad</button><p class="muted">Active ads appear automatically during their schedule when the placement is enabled. Rates are records only; this page does not collect payment.</p></form></dialog>
</body></html>
