import {track,observeAd,releaseAds} from './analytics.js?v=1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dialog=document.createElement('dialog');dialog.className='ad-dialog';document.body.append(dialog);let feed={ads:[],slots:{top:true,arrests:true,footer:false}},selectionSeed=Math.random();
function open(body){dialog.innerHTML='<div class="ad-dialog-header"><span>Business details</span><button type="button" class="ad-dismiss" aria-label="Close advertisement">Close ×</button></div><div class="ad-dialog-body">'+body+'</div>';dialog.querySelector('.ad-dismiss').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();dialog.querySelector('.ad-dialog-body').scrollTop=0;dialog.querySelector('.ad-dismiss').focus();}
function inquiry(slot='unsure'){open(`<span class="ad-label">ADVERTISE WITH LOCAL CRIMEWATCH</span><h2>Be seen in your community.</h2><p>Ask about space for your law firm, bail bond business, or local service. Send your details and we’ll discuss availability and pricing.</p><p>Advertising contact: <strong>info@crimewatch.live</strong></p><form id="sponsorInquiry"><label>Business name<input name="business" maxlength="100" required autocomplete="organization"></label><label>Your name<input name="name" maxlength="100" required autocomplete="name"></label><label>Email<input name="email" type="email" maxlength="160" required autocomplete="email"></label><label>Phone · optional<input name="phone" type="tel" maxlength="40" autocomplete="tel"></label><label>Placement<select name="slot"><option value="unsure">Help me choose</option><option value="top">Community banner</option><option value="arrests">Daily Arrests</option><option value="footer">Bottom banner</option></select></label><label>Tell us about your business<textarea name="message" rows="3" maxlength="2000" required></textarea></label><div class="ad-honeypot" aria-hidden="true"><label>Leave blank<input name="website" tabindex="-1" autocomplete="off"></label></div><p>These details are sent privately to the site owner to respond to your advertising request.</p><p id="inquiryStatus" role="status"></p><button type="submit">Send advertising inquiry</button></form>`);const form=dialog.querySelector('form');form.elements.slot.value=slot;form.onsubmit=async ev=>{ev.preventDefault();const button=form.querySelector('button');button.disabled=true;const status=dialog.querySelector('#inquiryStatus');try{const tokenResponse=await fetch('ads-api.php?action=inquiry-token',{cache:'no-store'});const token=await tokenResponse.json();if(!tokenResponse.ok)throw new Error(token.error);const r=await fetch('ads-api.php?action=inquiry',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':token.csrf},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const result=await r.json();if(!r.ok)throw new Error(result.error);open('<h2>Thank you for your interest.</h2><p>Your advertising inquiry has been sent to the site owner. We’ll use the contact details you provided to follow up.</p>');}catch(e){status.textContent=e.message||'Unable to send. Please try again.';status.className='ad-error';button.disabled=false;}};}
function profile(ad){open(`<span class="ad-label">PAID ADVERTISEMENT · ${esc(ad.category)}</span>${ad.image?`<img src="ads-image.php?file=${encodeURIComponent(ad.image)}" alt="${esc(ad.business)}">`:''}<h2>${esc(ad.business)}</h2><h3>${esc(ad.headline)}</h3><p>${esc(ad.body)}</p><div class="ad-contact">${ad.phone?`<p><strong>Phone:</strong> ${esc(ad.phone)}</p>`:''}${ad.email?`<p><strong>Email:</strong> ${esc(ad.email)}</p>`:''}</div><p>Paid advertising is not an endorsement by Local CrimeWatch.</p>`);}
function render(){
 const area=document.getElementById('area').value;
 for(const slot of ['top','arrests','footer']){
  const el=document.querySelector(`[data-ad-slot="${slot}"]`);if(!el)continue;
  el.hidden=!feed.slots[slot];if(el.hidden)continue;
  const ads=feed.ads.filter(a=>a.slot===slot&&(a.area==='all'||a.area===area));
  const ad=ads[Math.floor(selectionSeed*ads.length)];releaseAds(el);
  el.innerHTML=`<span class="ad-label">ADVERTISEMENT</span><button type="button" class="ad-card ${ad?.image?'ad-card--image':''}">${ad?.image?`<img src="ads-image.php?file=${encodeURIComponent(ad.image)}" alt="${esc(ad.business)} advertisement">`:''}<span class="ad-copy"><small>${esc(ad?ad.business:'LOCAL BUSINESSES · LOCAL REACH')}</small><strong>${esc(ad?ad.headline:'Your business. Right here in your community.')}</strong><span class="ad-description">${esc(ad?ad.body:'Advertising opportunities for attorneys, bail bond businesses, and local services.')}</span>${ad?.phone?`<span class="ad-phone">${esc(ad.phone)}</span>`:''}<span class="ad-cta">${ad?'View contact details':'Advertise here'} <span aria-hidden="true">→</span></span></span></button>`;
  const button=el.querySelector('button');observeAd(button,ad,slot);
  button.onclick=()=>{track(ad?'ad_click':'house_click',{ad_id:ad?.id||0,slot});ad?profile(ad):inquiry(slot);};
 }
}
document.getElementById('area').addEventListener('change',render);new MutationObserver(render).observe(document.getElementById('area'),{childList:true});render();
async function refresh(){try{const r=await fetch('ads-api.php?action=feed',{cache:'no-store'});if(r.ok){feed=await r.json();render();}}catch{}}
refresh();setInterval(refresh,60000);
