const optedOut=()=>{try{return localStorage.getItem('cw-analytics-optout')==='1'||navigator.doNotTrack==='1'||navigator.globalPrivacyControl===true;}catch{return true;}};
let tokenPromise=null;const sent=new Set();
function token(){return tokenPromise??=(async()=>{try{const r=await fetch('analytics-api.php?action=token',{cache:'no-store'});const d=await r.json();return r.ok?d.token:null;}catch{return null;}})();}
export async function track(event,{ad_id=0,slot='',area=document.getElementById('area')?.value||'polk'}={}){if(optedOut()||document.visibilityState!=='visible')return;const key=[event,area,slot,ad_id].join('|');if(sent.has(key))return;sent.add(key);const t=await token();if(!t)return;try{await fetch('analytics-api.php?action=event',{method:'POST',keepalive:true,headers:{'Content-Type':'application/json'},body:JSON.stringify({token:t,event,area,slot,ad_id})});}catch{}}
let observer;const timers=new Map();
export function releaseAds(container){for(const el of container.querySelectorAll('[data-metrics-ad]')){observer?.unobserve(el);if(timers.has(el)){clearTimeout(timers.get(el));timers.delete(el);}}}
export function observeAd(element,ad,slot){if(optedOut())return;if(!observer)observer=new IntersectionObserver(entries=>{for(const entry of entries){const el=entry.target;if(timers.has(el)){clearTimeout(timers.get(el));timers.delete(el);}if(entry.isIntersecting&&entry.intersectionRatio>=.5&&document.visibilityState==='visible'){timers.set(el,setTimeout(()=>{if(el.isConnected&&document.visibilityState==='visible')track(el.dataset.metricsAd==='0'?'house_impression':'ad_impression',{ad_id:Number(el.dataset.metricsAd),slot:el.dataset.metricsSlot,area:el.dataset.metricsArea});timers.delete(el);},1000));}}},{threshold:[0,.5,1]});element.dataset.metricsAd=String(ad?.id||0);element.dataset.metricsSlot=slot;element.dataset.metricsArea=document.getElementById('area')?.value||'polk';observer.observe(element);}
function view(){track('page_view');const arrests=document.getElementById('arrestsTab')?.getAttribute('aria-pressed')==='true';track(arrests?'arrests_view':'map_view');}
if(document.getElementById('mapTab')){view();for(const id of ['mapTab','arrestsTab'])document.getElementById(id).addEventListener('click',()=>setTimeout(view,0));document.getElementById('area').addEventListener('change',view);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')view();else{for(const t of timers.values())clearTimeout(t);timers.clear();}});}
