import {startWalkthrough} from './walkthrough.js?v=1';
import {requireAccount} from './auth.js';
await requireAccount();
import {locationPoint,locationError} from './location.js';
import {escapeHtml as e,charges,validPoint,dayLabel,arrestDates} from './model.js';
const $=id=>document.getElementById(id),cats={property:'Property',person:'Person',drugs:'Drugs / alcohol',other:'Other activity'},colors={property:'#b3954c',person:'#d37d69',drugs:'#8c7bb1',other:'#568b95'};
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const yesterday=new Date(today+'T12:00:00Z');yesterday.setUTCDate(yesterday.getUTCDate()-1);
const state={view:'map',offset:0,request:0,data:null,bookings:[],cell:null,points:[],controller:null};
try{$('area').innerHTML=`<option value="${e(localStorage.getItem('cw-area')||'polk')}">Polk County, TX</option>`;}catch{}
$('date').value=yesterday.toISOString().slice(0,10);$('date').max=today;
let map,layer,locationMarker,locationAccuracy,locationRequest=0,userLocation=null;
if(window.L){map=L.map('map',{scrollWheelZoom:false}).setView([30.79,-94.90],10);map.attributionControl.setPrefix('Leaflet');L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenStreetMap contributors · ODbL'}).on('tileerror',()=>{$('mapWarning').hidden=false;$('mapWarning').textContent='Some map tiles are unavailable. Reports are still available in the list.';}).addTo(map);layer=(L.markerClusterGroup?L.markerClusterGroup({maxClusterRadius:40,showCoverageOnHover:false,iconCreateFunction:c=>L.divIcon({className:"pin",html:String(c.getAllChildMarkers().reduce((n,m)=>n+(m.options.reportCount||1),0)),iconSize:[40,40]})}):L.layerGroup()).addTo(map);}else{$('mapWarning').hidden=false;$('mapWarning').textContent='The map could not load. Browse reports in the list.';}
function fit(){if(map&&state.points.length)map.fitBounds(state.points.map(p=>[p.lat,p.lng]),{padding:[45,45],maxZoom:12});}
const photo=r=>(r.photo_token||r.photo_bid)?`<img class="photo" src="jail-photo.php?${r.photo_token?'photo='+encodeURIComponent(r.photo_token):'bid='+encodeURIComponent(r.photo_bid)}" alt="${r.photo_token?'Photo from this published report':'Published booking photo'}" loading="lazy">`:'<div class="photo no-photo">Photo<br>unavailable</div>';
document.addEventListener('error',ev=>{if(ev.target.matches?.('img.photo')){const d=document.createElement('div');d.className='photo no-photo';d.textContent='Photo unavailable';ev.target.replaceWith(d);}},true);
async function json(path,signal){const r=await fetch(path,{signal});if(r.status===401){location.replace('account.php?required=1');throw Error('Please sign in to continue.');}if(!r.ok)throw Error('The report archive is temporarily unavailable. Please try Refresh.');return r.json();}
function note(message){$('notice').textContent=message;$('notice').hidden=!message;}
function open(html){$('detailBody').innerHTML=html;if(!$('detail').open)$('detail').showModal();$('detail').scrollTop=0;}
const innocence='<p class="innocence">Charges are not convictions. Everyone is presumed innocent until proven guilty.</p>';
function incident(r){open(`<p class="eyebrow">${e(cats[r.category]||'Reported activity')}</p><h2>${e(r.offense)}</h2><dl><div><dt>Incident / log date</dt><dd>${e(dayLabel(r.date))}</dd></div><div><dt>Published time</dt><dd>${e(r.time||'Not supplied')} ${r.time?'CT':''}</dd></div><div><dt>Reported location</dt><dd>${e(r.location||'Not supplied')}</dd></div><div><dt>Source / area</dt><dd>${e(r.agencyLabel)}</dd></div></dl>${Object.entries(r.details||{}).map(([k,v])=>`<p><strong>${e(k.replace(/([A-Z])/g,' $1'))}:</strong> ${e(v)}</p>`).join('')}<p>${r.sourceState==='not_listed'?'This saved record is no longer listed by the source. It may have been corrected or removed.':r.sourceState==='aged_out'?'Saved historical report; outside the current source window.':'Published activity report. Locations may be approximate.'}</p><p>Last verified: ${e(r.lastSeen||'Not supplied')}. A report does not establish guilt.</p>${innocence}`);}
function booking(r){open(`<p class="eyebrow">DAILY ARREST REPORT</p>${photo(r)}<h2>${e(r.name)}</h2><dl><div><dt>Arrest date</dt><dd>${e(arrestDates(r).join('; ')||'Not supplied')}</dd></div><div><dt>Booking date</dt><dd>${e(dayLabel(r.booked))}</dd></div><div><dt>Report date</dt><dd>${e(dayLabel(r.report_date))}</dd></div><div><dt>Release</dt><dd>${r.released?e(dayLabel(r.released)):'Not reported'}</dd></div></dl>${charges(r).map(c=>`<div class="charge"><h3>${e(c.description||'Charge not supplied')}</h3><p>${e(c.agency||'Agency not supplied')}<br>Arrest date: ${e(c.arrestDate||'Not supplied')}</p></div>`).join('')}${innocence}<p>Source: Polk County Sheriff’s Office booking reports, published by Polk County Today. Release not reported does not mean a person remains in custody.</p><p>No verified offense location is supplied with this booking record.</p>`);}
function renderBookings(){const q=$('search').value.trim().toLowerCase(),rows=state.bookings.filter(r=>r.name.toLowerCase().includes(q));$('arrests').innerHTML=rows.length?rows.map(r=>`<button class="booking" data-booking="${e(r.id)}">${photo(r)}<div><small>BOOKED ${e(dayLabel(r.booked))}</small><h3>${e(r.name)}</h3><p>Arrest: ${e(arrestDates(r).join('; ')||'Date not supplied')}</p>${charges(r).slice(0,2).map(c=>`<p>${e(c.description)}</p>`).join('')}<small>View details →</small></div></button>`).join(''):'<p class="empty">No matching records are available for this published report date. Try another date or clear the name search. This does not establish that no arrests occurred.</p>';$('arrestNote').innerHTML=`${rows.length} of ${state.bookings.length} people in this published report.`+(state.reportData?.sources||[]).map(source=>`<br>Report period: ${e(source.period_start)} through ${e(source.period_end)} CT`).join('');}
async function load(auto=false){state.controller?.abort();const control=new AbortController();state.controller=control;const request=++state.request;const signal=control.signal;note('');$('refresh').disabled=true;$('connection').textContent='Checking the archive…';$('updated').textContent='Checking source availability…';$('coverage').textContent='';$('reports').innerHTML='<p class="empty">Loading reports…</p>';$('arrests').innerHTML='<p class="empty">Loading daily report…</p>';layer?.clearLayers();state.data=null;state.bookings=[];state.points=[];$('prev').disabled=true;$('next').disabled=true;
try{if(state.view==='arrests'){
if($('area').value!=='polk'){$('arrestTitle').textContent='Daily reports not connected';$('arrestNote').textContent='';$('arrests').innerHTML='<p class="empty">Daily arrest coverage is currently available for Polk County only. Choose Polk County to browse its reports.</p>';$('connection').textContent='Coverage information';$('updated').textContent='No daily arrest source connected for this area.';return;}
const data=await json('jail-api.php?'+new URLSearchParams({report:auto?'latest':$('date').value}),signal);
if(request!==state.request)return;state.bookings=data.records;state.reportData=data;state.latest=data.archive?.latest;$('date').value=data.reportDate;$('arrestTitle').textContent=dayLabel(data.reportDate);renderBookings();
$('coverage').textContent='Polk County published daily reports · Each date includes everyone listed in that source report. Report periods use Central time.';
$('updated').textContent=data.checkedAt?'Source checked '+new Date(data.checkedAt).toLocaleString('en-US',{timeZone:'America/Chicago'})+' CT':'Source check time unavailable.';
$('connection').textContent='Published report archive connected';
if(auto&&data.reportDate<today)note(`The latest collected report is ${dayLabel(data.reportDate)}. A newer report is not available in the archive yet.`);
if(data.failedReports)note(($('notice').hidden?'':$('notice').textContent+' ')+'Some source reports are awaiting review; available reports may be incomplete.');
if(!data.checkedAt||Date.now()-new Date(data.checkedAt).getTime()>86400000)note(($('notice').hidden?'':$('notice').textContent+' ')+'Collection may be delayed. Check the report date before using these records.');
}else{
const p=new URLSearchParams({agency:$('area').value,period:$('period').value==='day'?'archive':$('period').value,category:$('category').value,q:$('search').value,offset:state.offset});if($('period').value==='day'){p.set('from',$('date').value);p.set('to',$('date').value);}if(state.cell){p.set('mapLat',state.cell.lat);p.set('mapLng',state.cell.lng);p.set('mapPrecision',state.cell.precision);}
const data=await json('api.php?'+p,signal);if(request!==state.request)return;state.data=data;const area=$('area').value;$('area').innerHTML='<option value="all">All covered communities</option>'+data.regions.map(r=>`<option value="${e(r.id)}">${e(r.label)}</option>`).join('');$('area').value=area;if(!$('area').value)$('area').value='polk';$('coverage').textContent=data.coverage||'Coverage varies by area.';$('count').textContent=data.summary.total;$('listTitle').textContent=state.cell?'At this map location':'Reported activity';$('reports').innerHTML=data.incidents.length?data.incidents.map(r=>`<button class="report" data-incident="${e(r.id)}"><div class="report-top"><i class="${Object.hasOwn(cats,r.category)?r.category:'other'}"></i>${e(cats[r.category]||'Other')}<time>${e(dayLabel(r.date))}</time></div><h3>${e(r.offense)}</h3><p>${e(r.location||'Location not supplied')}</p><small>${e(r.agencyLabel)}${validPoint(r)?'':' · Not mapped'}</small></button>`).join(''):'<p class="empty">No reports match these filters. Try a wider date range or another area.</p>';
$('page').textContent=data.incidents.length?`${state.offset+1}–${state.offset+data.incidents.length}`:'0 reports';$('prev').disabled=state.offset===0;$('next').disabled=!data.page.hasMore;state.points=data.map.points.filter(validPoint);if(layer)state.points.forEach(p=>{const category=Object.keys(cats).filter(k=>p[k]>0);const marker=L.marker([p.lat,p.lng],{icon:L.divIcon({className:'pin',html:String(Number(p.count)),iconSize:[32,32]}),reportCount:p.count,title:`${p.count} reported incidents`});if(category.length===1)marker.on('add',()=>{marker.getElement().style.background=colors[category[0]];});marker.on('click',()=>{const r=data.incidents.find(r=>r.id===p.id);if(p.count===1&&r)incident(r);else{state.cell={lat:p.lat,lng:p.lng,precision:data.map.precision};state.offset=0;load();}});layer?.addLayer(marker);});if(!state.cell&&!userLocation)fit();$('connection').textContent=data.stale?'Saved reports · collection delayed':'Incident archive connected';$('updated').textContent=`Source checked ${new Date(data.fetchedAt).toLocaleString('en-US',{timeZone:'America/Chicago'})} CT · ${data.map.unmapped} reports without coordinates`;if(data.stale)note('Source collection is delayed. Saved reports remain available.');
}}catch(err){if(err.name==='AbortError')return;note(err.message);$('connection').textContent='Reports unavailable';$('reports').innerHTML='<p class="empty">Could not load reports. Use Refresh to retry.</p>';$('arrests').innerHTML='<p class="empty">Could not load this daily report. Use Refresh to retry.</p>';$('count').textContent='—';$('page').textContent='';$('updated').textContent='Source could not be checked.';if(state.view==='arrests'){$('arrestTitle').textContent='Report unavailable';$('arrestNote').textContent='';}}finally{if(request===state.request)$('refresh').disabled=false;}}
function tab(view){locationRequest++;$('locate').disabled=false;$('locationControls').hidden=view!=='map';clearTimeout(timer);state.view=view;state.offset=0;state.cell=null;$('search').value='';$('mapTab').setAttribute('aria-pressed',String(view==='map'));$('arrestsTab').setAttribute('aria-pressed',String(view==='arrests'));$('mapView').hidden=view!=='map';$('arrestsView').hidden=view!=='arrests';$('categoryLabel').hidden=view!=='map';$('periodLabel').hidden=view!=='map';$('dateLabel').firstChild.textContent=view==='map'?'Report date':'Published report date';$('search').placeholder=view==='map'?'Search reports or locations':'Search by name';if(view==='map')requestAnimationFrame(()=>map?.invalidateSize());load(view==='arrests');}
$('mapTab').onclick=()=>tab('map');$('arrestsTab').onclick=()=>tab('arrests');$('refresh').onclick=()=>load();$('fit').onclick=()=>{if(state.cell){state.cell=null;state.offset=0;load();}else fit();};$('close').onclick=()=>$('detail').close();$('about').onclick=()=>open('<p class="eyebrow">ABOUT LOCAL CRIMEWATCH</p><h2>Local information, with context.</h2><p>Browse published incident reports and daily arrests from participating sources. Coverage is not comprehensive and publication may lag. Some areas cover a campus or a single agency.</p><p>Daily reports currently cover Polk County. Arrest dates appear as published. Choose a publication date to see everyone in that published report, including bookings on either side of midnight. The report period appears above the records.</p><p>Incident map dates come from incident logs. Arrests are not linked to map points unless a verified offense location is available. A residence or booking facility is not an offense location.</p>'+innocence);
$('area').onchange=()=>{try{localStorage.setItem('cw-area',$('area').value);}catch{}state.offset=0;state.cell=null;load(state.view==='arrests');};for(const id of ['date','category','period'])$(id).onchange=()=>{if(id==='date'&&state.view==='map')$('period').value='day';state.offset=0;state.cell=null;load();};let timer;$('search').oninput=()=>{clearTimeout(timer);if(state.view==='arrests')renderBookings();else timer=setTimeout(()=>{state.offset=0;state.cell=null;load();},300);};$('prev').onclick=()=>{state.offset=Math.max(0,state.offset-state.data.page.limit);load();};$('next').onclick=()=>{state.offset+=state.data.page.limit;load();};$('latest').onclick=()=>{$('date').value=state.latest||yesterday.toISOString().slice(0,10);load(true);};$('reports').onclick=ev=>{const b=ev.target.closest('[data-incident]');if(b){const r=state.data?.incidents.find(r=>r.id===b.dataset.incident);if(r)incident(r);}};$('arrests').onclick=ev=>{const b=ev.target.closest('[data-booking]');if(b){const r=state.bookings.find(r=>r.id===b.dataset.booking);if(r)booking(r);}};load();




$('locate').onclick=()=>{
 if(!map){$('locationStatus').textContent='The map is unavailable. Choose a community to browse reports.';return;}
 if(!navigator.geolocation){$('locationStatus').textContent='Location is not available in this browser. Choose a community manually.';return;}
 const request=++locationRequest;$('locate').disabled=true;$('locationStatus').textContent='Finding your location…';$('clearLocation').hidden=false;
 navigator.geolocation.getCurrentPosition(async position=>{
  if(request!==locationRequest)return;
  try{const point=locationPoint(position);userLocation=point;locationMarker?.remove();locationAccuracy?.remove();
   locationMarker=L.circleMarker([point.lat,point.lng],{radius:8,color:'#fff',weight:3,fillColor:'#3278bd',fillOpacity:1}).addTo(map).bindTooltip('Your approximate location');
   locationAccuracy=L.circle([point.lat,point.lng],{radius:point.accuracy,color:'#3278bd',weight:1,fillOpacity:.08}).addTo(map);
   map.setView([point.lat,point.lng],point.accuracy>5000?10:13);map.invalidateSize();
   if(!$('area').querySelector('option[value="all"]'))$('area').add(new Option('All covered communities','all'),0);
   $('area').value='all';state.cell=null;state.offset=0;
   $('locationStatus').textContent='Your approximate location is shown. Reports cover participating communities only; an empty map does not mean no crime.'+(point.accuracy>1000?' Your device reports limited location accuracy.':'');
   await load();
  }catch(error){$('locationStatus').textContent=error.message;}finally{if(request===locationRequest)$('locate').disabled=false;}
 },error=>{if(request!==locationRequest)return;$('locate').disabled=false;$('locationStatus').textContent=locationError(error);if(!userLocation)$('clearLocation').hidden=true;},{enableHighAccuracy:false,timeout:15000,maximumAge:60000});
};
$('clearLocation').onclick=()=>{locationRequest++;userLocation=null;locationMarker?.remove();locationAccuracy?.remove();locationMarker=null;locationAccuracy=null;$('clearLocation').hidden=true;$('locate').disabled=false;$('locationStatus').textContent='Location cleared.';fit();};

void startWalkthrough();
