<?php
declare(strict_types=1);require_once __DIR__.'/audience-lib.php';
function cw_member_db(): PDO {$db=cw_audience_db();$db->exec("CREATE TABLE IF NOT EXISTS member_tokens(hash TEXT PRIMARY KEY,reader_id INTEGER NOT NULL,expires INTEGER NOT NULL,created INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS member_codes(challenge TEXT PRIMARY KEY,email TEXT NOT NULL,hash TEXT NOT NULL,expires INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS member_devices(token TEXT PRIMARY KEY,reader_id INTEGER NOT NULL,enabled INTEGER NOT NULL DEFAULT 0,updated INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS push_campaigns(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,body TEXT NOT NULL,area TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',created TEXT NOT NULL);CREATE TABLE IF NOT EXISTS push_deliveries(campaign_id INTEGER NOT NULL,token TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',attempts INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(campaign_id,token));");return $db;}
function cw_bearer(): ?array {$header=$_SERVER['HTTP_AUTHORIZATION']??$_SERVER['REDIRECT_HTTP_AUTHORIZATION']??'';if(!preg_match('/^Bearer ([a-f0-9]{64})$/',$header,$m))return null;$st=cw_member_db()->prepare('SELECT r.id,r.email,r.name,r.area,r.created_at,r.verified_at FROM member_tokens t JOIN readers r ON r.id=t.reader_id WHERE t.hash=? AND t.expires>? AND r.verified_at IS NOT NULL');$st->execute([hash('sha256',$m[1]),time()]);return $st->fetch()?:null;}
function cw_member(): ?array {return cw_bearer()??cw_reader();}
function cw_owner_signed(): bool {cw_session();$a=cw_db()->query('SELECT version FROM admins WHERE id=1')->fetch();return $a&&($_SESSION['admin']??null)===1&&($_SESSION['version']??null)===(int)$a['version']&&time()-($_SESSION['active']??0)<=3600;}
function cw_report_access(): void {header('Cache-Control: private, no-store');header_register_callback(static function(){header('Cache-Control: private, no-store');});if(!cw_member()&&!cw_owner_signed())cw_json(['error'=>'Sign in to view CrimeWatch reports.','signInRequired'=>true],401);}
function cw_native_required(): array {$r=cw_bearer();if(!$r)cw_json(['error'=>'Sign in to your CrimeWatch account.'],401);return $r;}
function cw_forget_reader(int $id): void {$db=cw_member_db();$db->prepare('DELETE FROM member_tokens WHERE reader_id=?')->execute([$id]);$db->prepare('DELETE FROM push_deliveries WHERE token IN(SELECT token FROM member_devices WHERE reader_id=?)')->execute([$id]);$db->prepare('DELETE FROM member_devices WHERE reader_id=?')->execute([$id]);}
