<?php
declare(strict_types=1);require __DIR__.'/member-lib.php';header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');
try{
 $db=cw_member_db();$action=$_GET['action']??'';$method=$_SERVER['REQUEST_METHOD']??'GET';
 if($method==='GET'&&$action==='session'){$r=cw_bearer();cw_json(['reader'=>$r,'canViewReports'=>(bool)$r]);}
 if($method!=='POST')cw_json(['error'=>'Method not allowed'],405);$d=cw_input();
 if($action==='request-code'){
  cw_limit('member-request',5,3600);$email=strtolower(cw_text($d,'email',160,true));if(!filter_var($email,FILTER_VALIDATE_EMAIL)||($d['agree']??false)!==true)throw new InvalidArgumentException('Enter your email and acknowledge the privacy notice.');
  $st=$db->prepare('SELECT COUNT(*) FROM member_codes WHERE email=? AND expires>?');$st->execute([$email,time()-3000]);if((int)$st->fetchColumn()>=3)cw_json(['error'=>'Please wait before requesting another code.'],429);
  $challenge=bin2hex(random_bytes(32));$code=(string)random_int(10000000,99999999);$db->prepare('INSERT INTO member_codes(challenge,email,hash,expires) VALUES(?,?,?,?)')->execute([$challenge,$email,hash_hmac('sha256',$challenge.$code,cw_config()['secret']),time()+600]);
  $body="Your CrimeWatch sign-in code is: $code\n\nEnter this code in the CrimeWatch app within 10 minutes. Never share it. If you did not request it, ignore this email. Signing in verifies your email and creates your reader account if you are new. Notifications require a separate opt-in.\n\nCrimeWatch\ninfo@crimewatch.live";
  if(getenv('CW_ADS_TEST')==='1'){$ok=file_put_contents(cw_config()['dir'].'/test-code.json',json_encode(['challenge'=>$challenge,'code'=>$code,'email'=>$email]))!==false;}else{$ok=mail($email,'Your CrimeWatch sign-in code',$body,['From'=>'CrimeWatch <info@crimewatch.live>','Content-Type'=>'text/plain; charset=UTF-8'],'-finfo@crimewatch.live');}
  if(!$ok){$db->prepare('DELETE FROM member_codes WHERE challenge=?')->execute([$challenge]);cw_json(['error'=>'We could not send your code. Please try again later.'],503);}$db->prepare('DELETE FROM member_codes WHERE expires<?')->execute([time()-86400]);cw_json(['ok'=>true,'challenge'=>$challenge]);
 }
 if($action==='verify-code'){
  cw_limit('member-verify',20,900);$challenge=cw_text($d,'challenge',64,true);$code=cw_text($d,'code',8,true);$db->exec('BEGIN IMMEDIATE');$st=$db->prepare('SELECT * FROM member_codes WHERE challenge=? AND expires>? AND attempts<5');$st->execute([$challenge,time()]);$c=$st->fetch();
  if(!$c){$db->exec('ROLLBACK');cw_json(['error'=>'Code expired or used. Request a new code.'],403);}
  if(!hash_equals($c['hash'],hash_hmac('sha256',$challenge.$code,cw_config()['secret']))){$db->prepare('UPDATE member_codes SET attempts=attempts+1 WHERE challenge=?')->execute([$challenge]);$db->exec('COMMIT');cw_json(['error'=>'Incorrect code. Please check your email.'],403);}
  $now=gmdate('c');$db->prepare('INSERT OR IGNORE INTO readers(email,created_at) VALUES(?,?)')->execute([$c['email'],$now]);$db->prepare('UPDATE readers SET verified_at=COALESCE(verified_at,?),login_at=? WHERE email=?')->execute([$now,$now,$c['email']]);$st=$db->prepare('SELECT id,email,name,area FROM readers WHERE email=?');$st->execute([$c['email']]);$r=$st->fetch();$token=bin2hex(random_bytes(32));$db->prepare('INSERT INTO member_tokens VALUES(?,?,?,?)')->execute([hash('sha256',$token),$r['id'],time()+30*86400,time()]);$db->prepare('DELETE FROM member_codes WHERE email=?')->execute([$c['email']]);$db->prepare('DELETE FROM member_tokens WHERE expires<?')->execute([time()]);$db->exec('COMMIT');cw_json(['ok'=>true,'token'=>$token,'reader'=>$r]);
 }
 $r=cw_native_required();
 if($action==='save'){$name=cw_text($d,'name',80);$area=cw_text($d,'area',30,true);if(!cw_area($area))throw new InvalidArgumentException('Choose a community.');$db->prepare('UPDATE readers SET name=?,area=? WHERE id=?')->execute([$name,$area,$r['id']]);cw_json(['ok'=>true,'reader'=>cw_bearer()]);}
 if($action==='push'){$token=strtolower(cw_text($d,'token',512,true));if(!preg_match('/^[a-f0-9]{32,512}$/',$token)||!is_bool($d['enabled']??null))throw new InvalidArgumentException('Invalid notification registration.');$db->prepare('INSERT INTO member_devices VALUES(?,?,?,?) ON CONFLICT(token) DO UPDATE SET reader_id=excluded.reader_id,enabled=excluded.enabled,updated=excluded.updated')->execute([$token,$r['id'],$d['enabled']?1:0,time()]);if(!$d['enabled'])$db->prepare('DELETE FROM push_deliveries WHERE token=?')->execute([$token]);cw_json(['ok'=>true]);}
 if($action==='logout'){$header=$_SERVER['HTTP_AUTHORIZATION']??$_SERVER['REDIRECT_HTTP_AUTHORIZATION']??'';$db->prepare('DELETE FROM member_tokens WHERE hash=?')->execute([hash('sha256',substr($header,7))]);$token=cw_text($d,'deviceToken',512);if($token)$db->prepare('UPDATE member_devices SET enabled=0 WHERE token=? AND reader_id=?')->execute([$token,$r['id']]);cw_json(['ok'=>true]);}
 if($action==='delete'){if(($d['confirm']??'')!=='DELETE')throw new InvalidArgumentException('Type DELETE to confirm.');$db->beginTransaction();cw_forget_reader((int)$r['id']);$db->prepare('DELETE FROM reader_tokens WHERE email=?')->execute([$r['email']]);$db->prepare('DELETE FROM member_codes WHERE email=?')->execute([$r['email']]);$db->prepare('DELETE FROM readers WHERE id=?')->execute([$r['id']]);$db->commit();cw_json(['ok'=>true]);}
 cw_json(['error'=>'Unknown action'],404);
}catch(InvalidArgumentException $e){cw_json(['error'=>$e->getMessage()],400);}catch(Throwable $e){if(isset($db)&&$db->inTransaction())$db->rollBack();error_log('CrimeWatch member service: '.get_class($e));cw_json(['error'=>'Account service is temporarily unavailable.'],503);}
