<?php
declare(strict_types=1);require __DIR__.'/member-lib.php';header('Cache-Control: no-store');
try{cw_admin();$db=cw_member_db();$action=$_GET['action']??'list';
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='list')cw_json(['ready'=>is_file('/home1/crimewatch/alerts-service/config.json'),'devices'=>(int)$db->query('SELECT COUNT(*) FROM member_devices WHERE enabled=1')->fetchColumn(),'campaigns'=>$db->query("SELECT c.*, (SELECT COUNT(*) FROM push_deliveries d WHERE d.campaign_id=c.id) recipients,(SELECT COUNT(*) FROM push_deliveries d WHERE d.campaign_id=c.id AND d.status='sent') sent FROM push_campaigns c ORDER BY id DESC LIMIT 30")->fetchAll()]);
if($_SERVER['REQUEST_METHOD']!=='POST')cw_json(['error'=>'Method not allowed'],405);cw_csrf();$d=cw_input();
if($action==='draft'){$title=cw_text($d,'title',80,true);$body=cw_text($d,'body',240,true);$area=cw_text($d,'area',30,true);if(!cw_area($area,true))throw new InvalidArgumentException('Choose a valid community.');$db->prepare('INSERT INTO push_campaigns(title,body,area,created) VALUES(?,?,?,?)')->execute([$title,$body,$area,gmdate('c')]);$id=(int)$db->lastInsertId();$st=$db->prepare("SELECT COUNT(*) FROM member_devices d JOIN readers r ON r.id=d.reader_id WHERE d.enabled=1 AND r.verified_at IS NOT NULL AND (?='all' OR r.area=?)");$st->execute([$area,$area]);cw_audit('notification-draft',(string)$id);cw_json(['id'=>$id,'recipients'=>(int)$st->fetchColumn()]);}
if($action==='send'){
 if(($d['confirm']??'')!=='SEND')throw new InvalidArgumentException('Type SEND after reviewing the message.');if(!is_file('/home1/crimewatch/alerts-service/config.json')&&getenv('CW_ADS_TEST')!=='1')cw_json(['error'=>'Push delivery is not configured.'],503);
 $db->beginTransaction();$st=$db->prepare("SELECT * FROM push_campaigns WHERE id=? AND status='draft'");$st->execute([(int)($d['id']??0)]);$c=$st->fetch();if(!$c){$db->rollBack();cw_json(['error'=>'Draft no longer available.'],409);}
 $db->prepare("INSERT INTO push_deliveries(campaign_id,token) SELECT ?,d.token FROM member_devices d JOIN readers r ON r.id=d.reader_id WHERE d.enabled=1 AND r.verified_at IS NOT NULL AND (?='all' OR r.area=?)")->execute([$c['id'],$c['area'],$c['area']]);$count=(int)$db->query('SELECT changes()')->fetchColumn();$db->prepare('UPDATE push_campaigns SET status=? WHERE id=?')->execute([$count?'queued':'no recipients',$c['id']]);$db->commit();cw_audit('notification-queued',(string)$c['id']);cw_json(['ok'=>true,'recipients'=>$count]);
}
cw_json(['error'=>'Unknown action'],404);
}catch(InvalidArgumentException $e){cw_json(['error'=>$e->getMessage()],400);}catch(Throwable $e){if(isset($db)&&$db->inTransaction())$db->rollBack();error_log('CrimeWatch push admin: '.get_class($e));cw_json(['error'=>'Notification service unavailable.'],503);}
