const $=id=>document.getElementById(id);let reader,challenge='';function message(text){$('message').hidden=false;$('message').textContent=text;}
async function api(action,body){const r=await fetch('member-api.php?action='+action,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Please try again.');return d;}
function render(){ $('signIn').hidden=!!reader;$('profile').hidden=!reader;$('verify').hidden=true;if(reader){$('accountEmail').textContent=reader.email;$('profileForm').elements.name.value=reader.name;$('profileForm').elements.area.value=reader.area;localStorage.setItem('cw-area',reader.area);}}
const codeForm=document.createElement('form');codeForm.hidden=true;codeForm.innerHTML='<label>8-digit email code<input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{8}" maxlength="8" required></label><button class="primary">Verify and sign in</button>';$('signIn').append(codeForm);
$('signInForm').onsubmit=async ev=>{ev.preventDefault();const b=ev.target.querySelector('button');b.disabled=true;try{const d=await api('request-code',{email:ev.target.elements.email.value,agree:ev.target.elements.agree.checked});challenge=d.challenge;codeForm.hidden=false;message('Check your email and enter the 8-digit code here. It expires in 10 minutes.');}catch(e){message(e.message);}finally{b.disabled=false;}};
codeForm.onsubmit=async ev=>{ev.preventDefault();try{const d=await api('verify-code',{challenge,code:ev.target.elements.code.value});await window.CWStoreSession(d.token);await window.CWNotifications(false);reader=d.reader;render();message('You are signed in. Save your community or browse reports.');}catch(e){message(e.message);}};
$('profileForm').onsubmit=async ev=>{ev.preventDefault();try{reader=(await api('save',Object.fromEntries(new FormData(ev.target)))).reader;render();message('Profile saved.');}catch(e){message(e.message);}};
$('signOut').onclick=async()=>{try{await window.CWSignOut();location.reload();}catch(e){message(e.message);}};
$('deleteForm').onsubmit=async ev=>{ev.preventDefault();try{await api('delete',{confirm:ev.target.elements.confirm.value});await window.CWClearSession();location.reload();}catch(e){message(e.message);}};
const notifications=document.createElement('section');notifications.innerHTML='<h2>App notifications</h2><p>Optional announcements from CrimeWatch for your saved community. You can turn these off at any time.</p><button id="enablePush">Enable notifications</button><button id="disablePush">Turn off notifications</button><p id="pushPreference" role="status"></p>';$('profile').append(notifications);
for(const [id,enabled]of [['enablePush',true],['disablePush',false]])$(id).onclick=async()=>{$(id).disabled=true;try{await window.CWNotifications(enabled);$('pushPreference').textContent=enabled?'Notifications are on.':'Notifications are off.';}catch(e){$('pushPreference').textContent=e.message;}finally{$(id).disabled=false;}};
(async()=>{try{reader=(await api('session')).reader;render();$('pushPreference').textContent=await window.CWNotificationStatus()?'Notifications are on.':'Notifications are off.';}catch(e){message(e.message);}})();
