import {Capacitor,CapacitorHttp,registerPlugin} from '@capacitor/core';
import {Geolocation} from '@capacitor/geolocation';
import {PushNotifications} from '@capacitor/push-notifications';
import {Preferences} from '@capacitor/preferences';
const Secure=registerPlugin('CrimeWatchSession'),base='https://crimewatch.live/local/';let token='',pushToken='';
const ready=Secure.get().then(r=>token=r.value||'');window.CW_NATIVE=true;
window.CWStoreSession=async value=>{await Secure.set({value});token=value;};window.CWClearSession=async()=>{await Secure.remove();token='';};
const originalFetch=window.fetch.bind(window);
window.fetch=async(input,options={})=>{await ready;const url=new URL(String(input),location.href);if(!url.pathname.endsWith('.php'))return originalFetch(input,options);if(url.origin!==location.origin&&url.origin!=='https://crimewatch.live')throw Error('Unexpected API destination');const name=url.pathname.split('/').pop();if(!['api.php','jail-api.php','jail-photo.php','ads-api.php','ads-image.php','account-api.php','member-api.php','analytics-api.php'].includes(name))throw Error('This action is available on the website.');let target=base+name+url.search;if(name==='account-api.php'&&url.searchParams.get('action')==='session')target=base+'member-api.php?action=session';const headers={Origin:'https://crimewatch.live',...Object.fromEntries(new Headers(options.headers||{}))};if(token)headers.Authorization='Bearer '+token;if(options.signal?.aborted)throw new DOMException('Aborted','AbortError');const response=await CapacitorHttp.request({url:target,method:options.method||'GET',headers,data:options.body?JSON.parse(options.body):undefined,responseType:'json',connectTimeout:15000,readTimeout:30000});if(options.signal?.aborted)throw new DOMException('Aborted','AbortError');return new Response(JSON.stringify(response.data),{status:response.status,headers:{'Content-Type':'application/json'}});};
window.CWGetCurrentPosition=(success,failure,options)=>Geolocation.getCurrentPosition(options).then(success).catch(e=>failure({code:/denied|permission|0003|0009/i.test(String(e))?1:2}));
async function api(action,body){const r=await fetch('member-api.php?action='+action,{method:'POST',body:JSON.stringify(body),headers:{'Content-Type':'application/json'}});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
let registered;PushNotifications.addListener('registration',r=>{pushToken=r.value;Preferences.set({key:'crimewatch.member.device',value:pushToken});registered?.resolve(pushToken);registered=null;});PushNotifications.addListener('registrationError',()=>{registered?.reject(Error('Unable to register notifications. Try again.'));registered=null;});
window.CWNotifications=async enabled=>{await ready;if(enabled){const permission=await PushNotifications.requestPermissions();if(permission.receive!=='granted')throw Error('Allow notifications in iPhone Settings to enable them.');pushToken=await new Promise((resolve,reject)=>{registered={resolve,reject};PushNotifications.register().catch(reject);setTimeout(()=>{if(registered){registered=null;reject(Error('Notification registration timed out.'));}},15000);});}else if(!pushToken)pushToken=(await Preferences.get({key:'crimewatch.member.device'})).value||'';if(pushToken)await api('push',{token:pushToken,enabled});await Preferences.set({key:'crimewatch.member.push',value:enabled?'1':'0'});return enabled;};
window.CWNotificationStatus=async()=>{const pref=(await Preferences.get({key:'crimewatch.member.push'})).value==='1';const p=await PushNotifications.checkPermissions();return pref&&p.receive==='granted';};
window.CWSignOut=async()=>{pushToken=pushToken||(await Preferences.get({key:'crimewatch.member.device'})).value||'';await api('logout',{deviceToken:pushToken});await Preferences.set({key:'crimewatch.member.push',value:'0'});await window.CWClearSession();};
PushNotifications.addListener('pushNotificationActionPerformed',()=>{location.href='index.html';});
document.addEventListener('DOMContentLoaded',async()=>{document.body.classList.add('member-mobile');
 // Disable the previous app's anonymous alert registration when upgrading, then forget its local credentials.
 try{const old=(await Preferences.get({key:'crimewatch.pushIdentity'})).value;if(old){const identity=JSON.parse(old);if(identity.id&&identity.secret)await CapacitorHttp.post({url:'https://crimewatch.live/alerts-api.php',headers:{'Content-Type':'application/json','X-CrimeWatch-Device':identity.id,'X-CrimeWatch-Secret':identity.secret},data:{action:'disable'}});}}catch{}
 const observer=new MutationObserver(()=>{for(const img of document.querySelectorAll('img[data-native-image]')){const path=img.getAttribute('data-native-image');img.removeAttribute('data-native-image');void(async()=>{try{await ready;const url=new URL(path,base);if(url.origin!=='https://crimewatch.live'||!['/local/jail-photo.php','/local/ads-image.php'].includes(url.pathname))return;const r=await CapacitorHttp.get({url:url.href,headers:token?{Authorization:'Bearer '+token}:{},responseType:'arraybuffer'});if(r.status!==200)throw Error();const mime=r.headers['Content-Type']||r.headers['content-type']||'image/jpeg';img.src='data:'+mime+';base64,'+r.data;}catch{img.dispatchEvent(new Event('error'));}})();}});observer.observe(document.body,{childList:true,subtree:true});
});
